services:
  web:
    build: .
    command: gunicorn patients_management.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - sqlite_data:/app/data
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env.debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/patients/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    ports:
      - "8080:80"  # Host port 8080 maps to container port 80
    depends_on:
      web:
        condition: service_healthy

volumes:
  sqlite_data:
  static_volume:
