# Generated by Django 5.1.2 on 2025-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_doctor_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='dose',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Not Active')], default='pending', max_length=10),
        ),
    ]
