# Generated by Django 5.0.14 on 2025-04-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_prescribedmedicine_dose_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='past_illnesses',
        ),
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='dosage',
            field=models.CharField(default='1 per day', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GivedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_medicines', to='api.patient')),
                ('prescribed_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescribedmedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Past_Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_illnesses', to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='past_illness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.past_illness'),
        ),
    ]
