# Generated by Django 5.0.14 on 2025-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
