# Generated by Django 5.0.14 on 2025-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='past_illness',
        ),
        migrations.AlterModelOptions(
            name='prescribedmedicine',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='record',
            name='past_illnesses',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Past_Illness',
        ),
    ]
